config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "questions", to: "questions#ask"
  get "answers", to: "answers#read"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def read
    if @question = params[:question]
      if @question == 'I am going to work'
        @answer = 'Great!'
      elsif @question.include?('?')
        @answer = 'Silly question, get dressed and go to work!'
      else
        @answer = "I don't care, get dressed and go to work!"
      end
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def ask
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/read.html.erb
<h1>Stupid Coach</h1>

<hr>

<div class="card">
  <h5 class="card-header">You</h5>
  <div class="card-body">
    <p class="card-text"><%= @question %></p>
  </div>
</div>

<hr>

<div class="card">
  <h5 class="card-header">You coach</h5>
  <div class="card-body">
    <p class="card-text"><%= @answer %></p>
    <%= link_to "new question to you coach", questions_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

  </head>

  <body>
    <div class="container">
      <%= yield %>

    </div>
  </body>
</html>

app/views/questions/ask.html.erb
<%# <form  action="/answers" data-turbo="false"> %>
  <%# <input type="text" name="question"> %>
  <%# <input type="submit" value="Ask!"> %>
<%# </form> %>

<h1> Ask something to your coach</h1>

<hr>

<form action="/answers" data-turbo="false" class="input-group m-3">
  <input type="text" class="form-control" placeholder="ask a question" aria-label="Recipient's username" aria-describedby="button-addon2" name="question">
  <button class="btn btn-primary" type="submit" value="Ask!" id="button-addon2">Ask!</button>
</form>